version: '3'

services:
  dns:
    build: .
    container_name: dns
    restart: unless-stopped
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound/localzone:/etc/unbound/localzone:Z
    networks:
      internal_server:

networks:
  internal_server:
    external:
      name: vlan4020
