version: '3'

services:
  dns-mgmt:
    build: .
    #image: widecamp1903/unbound
    container_name: dns-mgmt
    restart: unless-stopped
    ports:
      - "10.0.156.130:53:53"
      - "10.0.156.130:53:53/udp"
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound/localzone:/etc/unbound/localzone:Z
    networks:
      mgmt:

  dns-internal-server:
    build: .
    #image: widecamp1903/unbound
    container_name: dns-internal-server
    restart: unless-stopped
    ports:
      - "203.178.156.130:53:53"
      - "203.178.156.130:53:53/udp"
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound/localzone:/etc/unbound/localzone:Z
    networks:
      internal_server:

networks:
  mgmt:
    external:
      name: vlan4000

  internal_server:
    external:
      name: vlan4020
