network:
    ethernets:
        ens192:
            addresses:
            - 10.0.156.130/16
            routes:
            - to: 0.0.0.0/0
              via: 10.0.0.1
              metric: 100
            nameservers:
                addresses:
                - 1.1.1.1
        ens160:
            addresses:
            - 203.178.156.130/26
            routes:
            - to: 0.0.0.0/0
              via: 203.178.156.129
              metric: 10
            nameservers:
                addresses:
                - 1.1.1.1
    version: 2
